export const REQUEST_INCIDENTS = 'REQUEST_INCIDENTS';
export const RECEIVE_INCIDENTS = 'RECEIVE_INCIDENTS';
export const CREATE_INCIDENT = 'CREATE_INCIDENT';
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION';
export const SET_FOCUS = 'SET_FOCUS';

export const SET_LIST_OF_PAGES = 'SET_LIST_OF_PAGES';